version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - psql --version
      - sudo yum update -y
      - sudo yum install -y postgresql
      - sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      - sudo yum install -y postgresql11

  build:
    commands:
      - pwd
      # Verify libpq installation
      - psql --version
      # - sudo amazon-linux-extras enable epel
      # - sudo yum install postgresql-devel
      # - sudo yum install -y libpq
      # - psql --version
      # - yum list available | grep postgresql
      # - yum list installed | grep libpq
      # - rpm -qa | grep libpq
      # - dpkg -l | grep libpq
      - ls -la
      - psql -h "sd-db1.c76o4qoeq8xw.us-east-1.rds.amazonaws.com" -U "postgres" -d "sd_firstdb" -c "SELECT 1;"
      - . ./sd-script1.sh
