version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - sudo yum update -y
      - sudo yum install -y postgresql

  build:
    commands:
       - pwd 
       - ls -la
       - . ./sd-script1.sh
