version: 0.2

phases:
  install:
    runtime-versions:
      amazon-linux: latest
    commands:
      # Install build tools and dependencies
      - sudo yum install -y gcc make wget

  build:
    commands:
      # Download PostgreSQL source code
      - wget https://ftp.postgresql.org/pub/source/v13.4/postgresql-13.4.tar.gz
      - tar -zxvf postgresql-13.4.tar.gz
      - cd postgresql-13.4

      # Configure, compile, and install libpq
      - ./configure
      - make
      - sudo make install

      # Verify libpq installation
      - psql --version
