
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - sudo yum update -y
      - sudo yum install -y postgresql

  build:
    commands:
       - pwd 
       - rpm -qa | grep libpq
       - dpkg -l | grep libpq
       - ls -la
       - psql -h "sd-db1.c76o4qoeq8xw.us-east-1.rds.amazonaws.com" -U "postgres" -d "sd_firstdb" -c "SELECT 1;" 
       - . ./sd-script1.sh
