version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
  

  build:
    commands:
      # Set up PostgreSQL Yum Repository
      - sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

      # Install libpq
      - sudo yum install -y postgresql10
      - psql --version
      - ls -la
      - psql -h "sd-db1.c76o4qoeq8xw.us-east-1.rds.amazonaws.com" -U "postgres" -d "sd_firstdb" -c "SELECT 1;" 
      - . ./sd-script1.sh
