version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      
  build:
    commands:
       - . ./postgresql-client.sh
       - sudo yum update -y
       - sudo yum install postgresql -y
   #   - chmod +x ./sd-db/sd-script1.sh
   #   - ./sd-db/sd-script1.sh
       - pwd 
       - ls -la
       - . ./sd-script1.sh
